### ISSUE TITLE
1.17 Compatibility.

### ISSUE THREAD

**Issue by RealTriassic** [CodeCrafter47/AdvancedTabOverlay#20]
The plugin does not load on Minecraft 1.17 server versions.

```[02:58:02 ERROR]: Error occurred while enabling AdvancedTabOverlay v1.3.0-SNAPSHOT (Is it up to date?)
java.lang.IllegalStateException: Unsupported Minecraft version
        at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.SafeTabOverlayHandlerFactory.<init>(SafeTabOverlayHandlerFactory.java:56) ~[?:?]
        at de.codecrafter47.taboverlay.bukkit.AdvancedTabOverlay.onEnable(AdvancedTabOverlay.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:715) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1206]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[02:58:02 INFO]: [AdvancedTabOverlay] Disabling AdvancedTabOverlay v1.3.0-SNAPSHOT
[02:58:02 ERROR]: Error occurred while disabling AdvancedTabOverlay v1.3.0-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "de.codecrafter47.taboverlay.bukkit.TabOverlayHandlerFactory.onDisable()" because "this.tabOverlayHandlerFactory" is null
        at de.codecrafter47.taboverlay.bukkit.AdvancedTabOverlay.onDisable(AdvancedTabOverlay.java:270) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:405) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:533) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.17.jar:git-Purpur-1206]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:715) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:315) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[patched_1.17.jar:git-Purpur-1206]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.jar:git-Purpur-1206]
        at java.lang.Thread.run(Thread.java:831) [?:?]```

**Comment by CodeCrafter47** [comment]
1.17 is now supported by the latest version of the plugin.
