### ISSUE TITLE
yo 1.19.1 support gaming would be cool

### ISSUE THREAD

**Issue by hypigler** [CodeCrafter47/AdvancedTabOverlay#28]
Currently on 1.19.1, this spams the console when player is existing in server.

Using dev build #165.
As well as Protocollib dev build #585.

```
[15:58:07] [defaultEventExecutorGroup-2-1/ERROR]: [AdvancedTabOverlay] Unexpected exception
java.lang.NoSuchMethodError: com/comphenix/protocol/reflect/accessors/Accessors.getFieldAccessor(Ljava/lang/Class;Ljava/lang/String;Z)Lcom/comphenix/protocol/reflect/accessors/FieldAccessor; (loaded from file:/home/container/plugins/ProtocolLib.jar by PluginClassLoader{plugin=ProtocolLib v5.0.0-SNAPSHOT-b585, pluginEnabled=true, url=plugins/ProtocolLib.jar}) called from class de.codecrafter47.taboverlay.bukkit.internal.ATODataAccess (loaded from file:/home/container/plugins/AdvancedTabOverlay-1.4.0-SNAPSHOT.jar by PluginClassLoader{plugin=AdvancedTabOverlay v1.4.0-SNAPSHOT, pluginEnabled=true, url=plugins/AdvancedTabOverlay-1.4.0-SNAPSHOT.jar}).
    at de.codecrafter47.taboverlay.bukkit.internal.ATODataAccess.getPlayerPing(ATODataAccess.java:76) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.taboverlay.bukkit.internal.ATODataAccess$$Lambda$9818/0x0000000080a28d48.apply(Unknown Source) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.data.api.AbstractDataAccess$$Lambda$9800/0x0000000080a23010.apply(Unknown Source) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.taboverlay.bukkit.internal.DataManager$PlayerDataHolder.update(DataManager.java:101) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.taboverlay.bukkit.internal.DataManager.updateData(DataManager.java:69) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at de.codecrafter47.taboverlay.bukkit.internal.DataManager$$Lambda$9823/0x0000000080a2a340.run(Unknown Source) ~[AdvancedTabOverlay-1.4.0-SNAPSHOT.jar:?]
    at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.77.Final.jar:4.1.77.Final]
    at java.lang.Thread.run(Thread.java:884) ~[?:?]
```

**Comment by Andre601** [comment]
The error is about a missing method within ProtocolLib which ATO depends on, so it technically isn't an incompatibility with 1.19.1 but with ProtocolLib
