### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by llronaldoll** [CodeCrafter47/AdvancedTabOverlay#3]
[22:14:29] [Netty Server IO #0/WARN]: java.lang.NullPointerException
[22:14:29] [Netty Server IO #0/WARN]: 	at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.CustomContentOperationModeHandler.onPlayerRemoved(CustomContentOperationModeHandler.java:212)
[22:14:29] [Netty Server IO #0/WARN]: 	at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.VanillaTabOverlayTracker.fireOnPlayerRemoved(VanillaTabOverlayTracker.java:205)
[22:14:29] [Netty Server IO #0/WARN]: 	at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.VanillaTabOverlayTracker.onPacketSending(VanillaTabOverlayTracker.java:90)
[22:14:29] [Netty Server IO #0/WARN]: 	at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.SafeTabOverlayHandler.onPacketSending(SafeTabOverlayHandler.java:34)
[22:14:29] [Netty Server IO #0/WARN]: 	at de.codecrafter47.taboverlay.bukkit.internal.handler.safe.SafeTabOverlayHandlerFactory$MyChannelHandler.write(SafeTabOverlayHandlerFactory.java:77)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300)
[22:14:29] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelProxy.writeAndFlush(ChannelProxy.java:327)
[22:14:29] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_14_R1.NetworkManager.lambda$4(NetworkManager.java:190)
[22:14:29] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$3.lambda$onMessageScheduled$1(ChannelInjector.java:307)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[22:14:29] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[22:14:29] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by llronaldoll** [comment]
This is happening every time a player tries to connect, everything seemed to work fine until all were kicked and can no longer come back.

**Comment by Andre601** [comment]
Server type an version? ProtocolLib installed and running?
Also, please use https://hasteb.in for sharing.

**Comment by llronaldoll** [comment]
server 1.14.4, ProtocolLib up and running, as I said everything looked normal, but all were kicked in and unable to log in unless I remove AdvancedTabOverlay

**Comment by Andre601** [comment]
Your error points to [this line in the code](https://github.com/CodeCrafter47/AdvancedTabOverlay/blob/master/src/main/java/de/codecrafter47/taboverlay/bukkit/internal/handler/safe/CustomContentOperationModeHandler.java#L212) and from my understanding is it most likely an issue with getting the UUID of a player.

Do you perhaps run the server in offline mode? Or any other specific settings (BungeeCord network, mods, etc.)?

**Comment by llronaldoll** [comment]
I run offline, but it also has problems when players with official account enter

**Comment by Andre601** [comment]
> I run offline, but it also has problems when players with official account enter

This doesn't matter. In offline mode are the UUIDs not the same one as valid accounts have. The server creates own ones based on the name of the player (Which is why you shouldn't run offline servers in the first place).
So it's not surprising that the plugin gets an issue with retrieving the UUID of (I guess) a player since the UUID is not the same, therefore it can't get the skin or other data from it.

**Comment by llronaldoll** [comment]
Is there a possibility to add offline server support?

**Comment by CodeCrafter47** [comment]
I do not think this issue is related to running an offline server. I believe the latest commit might have fixed this issue, but I cannot tell for sure since I cannot reproduce this issue on my setup. Just try the latest build from jenkins and check if the issue is fixed.

**Comment by llronaldoll** [comment]
I installed the new build and the problem seems to be solved, thanks friend good work, I will continue testing if another problem appears I post here!

**Comment by llronaldoll** [comment]
Can you tell me where I get the placeholders that work in the plugin?

**Comment by Andre601** [comment]
You can use all PlaceholderAPI placeholders using either the `player` or `viewer` option.
Example: `${player vault_group}` and `${viewer vault_group}`

All other placeholders are on the wiki: https://github.com/CodeCrafter47/AdvancedTabOverlay/wiki/Placeholders

**Comment by llronaldoll** [comment]
Can you tell me why the icon doesn't appear?

**Comment by Andre601** [comment]
Icons aren't displayed on offline servers.
Iirc can you use SkinRestorer to *fix* this

**Comment by llronaldoll** [comment]
I use skinrestorer, how do I fix it?

**Comment by Andre601** [comment]
No idea.

**Comment by llronaldoll** [comment]
can you please show me your AdvancedTabOverlay configuration file? so I can get an idea how to set up

**Comment by CodeCrafter47** [comment]
A list of placeholders is available on the wiki: <https://github.com/CodeCrafter47/AdvancedTabOverlay/wiki/Placeholders>. As already mentioned, you can also use placeholders from PlaceholderAPI.

Icons are not displayed on offline mode servers. SkinRestorer cannot fix that. However it may be possible for premium players to see icons when connected to an offline mode server. For this to happen the server needs to authenticate the player with mojang servers as it would if the server was an online mode server. Some of the authentication plugins typically used on offline mode servers offer this functionality. While its primary goal is to simplify the life of premium players by not having them type a password, it should also allow those players to see the icons.

You can read through the wiki for configuration help. Various pages contain examples of configuration files. It is not complete yet, but should give you an idea.

**Comment by llronaldoll** [comment]
> A list of placeholders is available on the wiki: https://github.com/CodeCrafter47/AdvancedTabOverlay/wiki/Placeholders. As already mentioned, you can also use placeholders from PlaceholderAPI.
> 
> Icons are not displayed on offline mode servers. SkinRestorer cannot fix that. However it may be possible for premium players to see icons when connected to an offline mode server. For this to happen the server needs to authenticate the player with mojang servers as it would if the server was an online mode server. Some of the authentication plugins typically used on offline mode servers offer this functionality. While its primary goal is to simplify the life of premium players by not having them type a password, it should also allow those players to see the icons.
> 
> You can read through the wiki for configuration help. Various pages contain examples of configuration files. It is not complete yet, but should give you an idea.



it may take me a while, I'm trying to add a second line to the footer, but whenever I do that the plugin stops working

________________________

footer: # The footer text:
- |-
  &6Line 1
  &eLine 2

**Comment by Andre601** [comment]
I thought this was something SkinRestorer *"fixes"* since I once had an offline server and even tho I have a premium account to that time, did icons not show in tab... Only after I added the plugin did it show... So perhaps it has some sort of authentication system in place? I don't know. It was quite some time ago so I can remember it wrong.

**Comment by llronaldoll** [comment]
which authentication plugin do you use?

**Comment by llronaldoll** [comment]
> I thought this was something SkinRestorer _"fixes"_ since I once had an offline server and even tho I have a premium account to that time, did icons not show in tab... Only after I added the plugin did it show... So perhaps it has some sort of authentication system in place? I don't know. It was quite some time ago so I can remember it wrong.

which authentication plugin do you use?

**Comment by llronaldoll** [comment]
> A list of placeholders is available on the wiki: https://github.com/CodeCrafter47/AdvancedTabOverlay/wiki/Placeholders. As already mentioned, you can also use placeholders from PlaceholderAPI.
> 
> Icons are not displayed on offline mode servers. SkinRestorer cannot fix that. However it may be possible for premium players to see icons when connected to an offline mode server. For this to happen the server needs to authenticate the player with mojang servers as it would if the server was an online mode server. Some of the authentication plugins typically used on offline mode servers offer this functionality. While its primary goal is to simplify the life of premium players by not having them type a password, it should also allow those players to see the icons.
> 
> You can read through the wiki for configuration help. Various pages contain examples of configuration files. It is not complete yet, but should give you an idea.

![image](https://user-images.githubusercontent.com/5334591/66364677-f353d300-e960-11e9-92bb-e06d7d96ca9e.png)

**Comment by Andre601** [comment]
I think this is no longer up to date since no response or anything has been made.
