### ISSUE TITLE
1.20.1 Plugin issues

### ISSUE THREAD

**Issue by mtmtyu** [CodeCrafter47/AdvancedTabOverlay#33]
An error occurred and the plugin is not working properly.

```
[17:31:59 ERROR]: [AdvancedTabOverlay] Unexpected exception
java.lang.RuntimeException: Exception while querying data from Vault
Vault 1.7.3-b131
Permissions LuckPerms 5.4.102
Chat LuckPerms 5.4.102
Economy TheNewEconomy 0.1.2.0

        at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:35) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.taboverlay.bukkit.internal.DataManager$PlayerDataHolder.update(DataManager.java:101) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.taboverlay.bukkit.internal.DataManager.updateData(DataManager.java:69) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.87.Final.jar:4.1.87.Final]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.util.NoSuchElementException
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1599) ~[?:?]
        at java.util.HashMap$ValueIterator.next(HashMap.java:1625) ~[?:?]
        at net.tnemc.core.manager.CurrencyManager.getDefaultCurrency(CurrencyManager.java:131) ~[TNE-BukkitCore-0.1.2.5.jar:?]
        at net.tnemc.core.manager.CurrencyManager.getDefaultCurrency(CurrencyManager.java:152) ~[TNE-BukkitCore-0.1.2.5.jar:?]
        at net.tnemc.bukkit.hook.economy.TNEVault.getBalance(TNEVault.java:188) ~[TNE-BukkitCore-0.1.2.5.jar:?]
        at net.tnemc.bukkit.hook.economy.TNEVault.getBalance(TNEVault.java:176) ~[TNE-BukkitCore-0.1.2.5.jar:?]
        at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:48) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.bukkit.vault.VaultBalanceProvider.apply0(VaultBalanceProvider.java:29) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at de.codecrafter47.data.bukkit.vault.VaultDataProvider.apply(VaultDataProvider.java:33) ~[AdvancedTabOverlay-1.3.5.jar:?]
        ... 14 more
```

**Comment by mtmtyu** [comment]
I get the same error whether I use the release version or the latest dev version.

**Comment by Andre601** [comment]
The error says "NoSuchElementException" which tells me the plugin tried to access something that doesn't exist...
Tho, I cannot say what it tried to access exactly and where... It could be that the TheNewEconomy plugin made changes to their API?

This is honestly just guessing on my end as I'm not sure if that plugin is actually supported by ATO.

**Comment by mtmtyu** [comment]
It seems that the cause is that the TNE plugin corrupted the currency data, making it impossible for this plugin to access the data. This problem is resolved. thank you very much
