### ISSUE TITLE
Ping error spam in console

### ISSUE THREAD

**Issue by Chopnex** [CodeCrafter47/AdvancedTabOverlay#34]
[21:17:02 ERROR]: [AdvancedTabOverlay] Unexpected exception
java.lang.NoSuchMethodError: 'int org.bukkit.entity.Player.getPing()'
        at de.codecrafter47.taboverlay.bukkit.internal.ATODataAccess.getPlayerPing(ATODataAccess.java:73) ~[?:?]
        at de.codecrafter47.data.api.AbstractDataAccess.lambda$addProvider$0(AbstractDataAccess.java:30) ~[?:?]
        at de.codecrafter47.data.api.AbstractDataAccess.get(AbstractDataAccess.java:44) ~[?:?]
        at de.codecrafter47.data.bukkit.AbstractBukkitDataAccess.get(AbstractBukkitDataAccess.java:43) ~[?:?]
        at de.codecrafter47.data.api.JoinedDataAccess.get(JoinedDataAccess.java:40) ~[?:?]
        at de.codecrafter47.taboverlay.bukkit.internal.DataManager$PlayerDataHolder.update(DataManager.java:101) ~[?:?]
        at de.codecrafter47.taboverlay.bukkit.internal.DataManager.updateData(DataManager.java:69) ~[?:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:159) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git-PaperSpigot-cbe632ca]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[server.jar:git-PaperSpigot-cbe632ca]

**Comment by Andre601** [comment]
Please read the plugin page next time. As this matrix shows is ATO not compatible with ANY 1.8 versions, which you are using based on your statement in the discord server:
![grafik](https://github.com/CodeCrafter47/AdvancedTabOverlay/assets/11576465/ec74287f-efd0-4942-956b-07daa5a011ea)

**Comment by Chopnex** [comment]
Andre, the plugin literally works perfect except for this bug. Even viaversion joining with 1.20 on my 1.8 server works perfectly. This could probably be fixed so easy!

**Comment by Andre601** [comment]
If it can be fixed that easily, go ahead. The code is here for you to change.
Never claim a fix is "easy" if you don't know the fix.

And this is my personal view now, but your main issue is using 1.8.9. That version is ancient and no sane person should use it anymore.
Also, given the matrix I shared are you causing the issue yourself because - as is clearly shown - any Server version between 1.8 and 1.16 is not considered compatible with *any* client version.

**Comment by Chopnex** [comment]
Im not claiming it can be fixed easily, sorry for that. Im just saying it looks like its not that hard to fix. The only reason why im using this plugin now is because I recently transfered to Velocity and can no longer use BTLP. ATO works very well for me, just thought codecrafter wanted to fix this simple thing to make 1.8 servers be able to use the plugin since where im from (Denmark) this is still the most popular mc version.

**Comment by Chopnex** [comment]
And the plugin works; placeholders, custom groups, animations and everything I am using so far. Im just annoyed by the fact that my console is getting spammed :))
