### ISSUE TITLE
Headers and footers don't work on 1.20.6, 1.21 and 1.21.1

### ISSUE THREAD

**Issue by EpicKnarvik97** [CodeCrafter47/AdvancedTabOverlay#35]
On Paper 1.20.6+, the plugin will produce the following error:

```
[22:13:51 ERROR]: [AdvancedTabOverlay] Failed to activate tab overlay plugins\AdvancedTabOverlay\tabLists\default.yml
java.lang.IllegalStateException: Unable to invoke method public static net.minecraft.network.chat.MutableComponent net.minecraft.network.chat.Component$Serializer.fromJson(java.lang.String,net.minecraft.core.HolderLookup$Provider)
        at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:25) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.WrappedChatComponent.deserialize(WrappedChatComponent.java:95) ~[ProtocolLib.jar:?]
        at ProtocolLib.jar/com.comphenix.protocol.wrappers.WrappedChatComponent.fromJson(WrappedChatComponent.java:135) ~[ProtocolLib.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.bukkit.internal.handler.simple.SimpleTabOverlayHandler$CustomHeaderAndFooterOperationModeHandler$Representation.setHeaderFooter(SimpleTabOverlayHandler.java:219) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.view.HeaderAndFooterView.updateHeaderAndFooter(HeaderAndFooterView.java:72) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.view.HeaderAndFooterView.onActivation(HeaderAndFooterView.java:57) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.view.AbstractActiveElement.activate(AbstractActiveElement.java:97) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.view.TabOverlayView.<init>(TabOverlayView.java:50) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.view.TabOverlayView.create(TabOverlayView.java:41) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at AdvancedTabOverlay-1.3.5.jar/de.codecrafter47.taboverlay.config.ConfigTabOverlayProvider.lambda$onActivate$1(ConfigTabOverlayProvider.java:75) ~[AdvancedTabOverlay-1.3.5.jar:?]
        at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: com.google.gson.JsonParseException: Not a boolean: "true"
        at com.mojang.serialization.DataResult$Error.getOrThrow(DataResult.java:287) ~[datafixerupper-8.0.16.jar:?]
        at net.minecraft.network.chat.Component$Serializer.deserialize(Component.java:296) ~[paper-1.21.jar:1.21-111-66165f7]
        at net.minecraft.network.chat.Component$Serializer.fromJson(Component.java:311) ~[paper-1.21.jar:1.21-111-66165f7]
        at ProtocolLib.jar/com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:23) ~[ProtocolLib.jar:?]
        ... 17 more
```

If showHeaderFooter is set to false, the plugin will work as expected. This error happens with the default configuration generated by the plugin. Both 5.2.0 and the latest dev build of ProtocolLib causes this behavior. Older versions cannot be tested, as those do not support 1.20.6+.

**Comment by EpicKnarvik97** [comment]
While the problem exists for the version published to Spigot, the latest DEV version (1.4.0) does not have this problem.
